import { copyFileSync, mkdirSync } from "fs";
import { globSync } from "glob";
import stdLibBrowser from "node-stdlib-browser";
// import { polyfillNode } from "esbuild-plugin-polyfill-node";
import plugin from "node-stdlib-browser/helpers/esbuild/plugin";
import { dirname } from "path";
import { defineConfig } from "tsup";

// import shim from "node-stdlib-browser/helpers/esbuild/shim";

export default defineConfig((options) => ({
  // shims: true,
  entry: ["src/**/*.ts", "src/**/*.tsx", "!src/**/*.test.*"],
  bundle: false,
  splitting: false,
  // minify: !options.watch,
  format: ["cjs", "esm"],
  target: "es2020",
  sourcemap: true,
  clean: !options.watch,
  dts: false, // d.ts files are generated by tsc, not tsup
  noExternal: ["bs58", "@noble/ed25519"],
  external: ["ethers", "ethers-decode-error"],
  esbuildPlugins: [
    plugin(stdLibBrowser),
    // polyfillNode({
    //   polyfills: {
    //     buffer: true,
    //     // crypto: true,
    //   },
    // }),
  ],
  esbuildOptions(options, context) {
    options.define.Buffer = "Buffer";
    options.define.process = "process";
    options.define.global = "global";
    options.inject = [
      require.resolve("node-stdlib-browser/helpers/esbuild/shim"),
    ];
    if (!options.watch) {
      options.drop = ["debugger"];
    }
  },
  tsconfig: "tsconfig.build.json",
  async onSuccess() {
    // Copy JSON files to dist, preserving directory structure
    const jsonFiles = globSync("src/**/*.json");
    for (const file of jsonFiles) {
      const destPath = file.replace(/^src/, "dist");
      mkdirSync(dirname(destPath), { recursive: true });
      copyFileSync(file, destPath);
      console.log(`Copied: ${file} -> ${destPath}`);
    }
  },
}));
